export const nameOfCoins = [
    { nameEng: "BTC", nameKor: "비트코인" },
    { nameEng: "BSV", nameKor: "비트코인에스브이" },
    { nameEng: "XRP", nameKor: "리플" },
    { nameEng: "BCH", nameKor: "비트코인 캐시" },
    { nameEng: "EOS", nameKor: "이오스" },
    { nameEng: "ETH", nameKor: "이더리움" },
    { nameEng: "ETC", nameKor: "이더리움 클래식" },
    { nameEng: "XSR", nameKor: "젠서" },
    { nameEng: "BTG", nameKor: "비트코인 골드" },
    { nameEng: "TRX", nameKor: "트론" },
    { nameEng: "LTC", nameKor: "라이트코인" },
    { nameEng: "QTUM", nameKor: "퀀텀" },
    { nameEng: "SOC", nameKor: "소다코인" },
    { nameEng: "LUNA", nameKor: "루나" },
    { nameEng: "ADA", nameKor: "에이다" },
    { nameEng: "GNT", nameKor: "골렘" },
    { nameEng: "DAD", nameKor: "다드" },
    { nameEng: "IPX", nameKor: "타키온프로토콜" },
    { nameEng: "TRV", nameKor: "트러스트버스" },
    { nameEng: "XLM", nameKor: "스텔라루멘" },
    { nameEng: "BCD", nameKor: "비트코인 다이아몬드" },
    { nameEng: "MTL", nameKor: "메탈" },
    { nameEng: "AE", nameKor: "애터니티" },
    { nameEng: "LINK", nameKor: "체인링크" },
    { nameEng: "TMTG", nameKor: "더마이다스터치골드" },
    { nameEng: "STEEM", nameKor: "스팀" },
    { nameEng: "WTC", nameKor: "월튼체인" },
    { nameEng: "AOA", nameKor: "오로라" },
    { nameEng: "REP", nameKor: "어거" },
    { nameEng: "CON", nameKor: "코넌" },
    { nameEng: "FCT", nameKor: "피르마체인" },
    { nameEng: "DASH", nameKor: "대시" },
    { nameEng: "THETA", nameKor: "쎄타토큰" },
    { nameEng: "FNB", nameKor: "애프앤비프로토콜" },
    { nameEng: "FAB", nameKor: "패블릭" },
    { nameEng: "BTT", nameKor: "비트토렌트" },
    { nameEng: "VALOR", nameKor: "밸러토큰" },
    { nameEng: "GXC", nameKor: "지엑스체인" }
  ];
  
  export const nameOfCoins2 = [
    { nameEng: "AMO", nameKor: "아모코인" },
    { nameEng: "MXC", nameKor: "머신익스체인지코인" },
    { nameEng: "VET", nameKor: "비체인" },
    { nameEng: "ZEC", nameKor: "제트캐시" },
    { nameEng: "WAVES", nameKor: "웨이브" },
    { nameEng: "OMG", nameKor: "오미세고" },
    { nameEng: "ENJ", nameKor: "엔진코인" },
    { nameEng: "PIVX", nameKor: "피벡스" },
    { nameEng: "LAMB", nameKor: "람다" },
    { nameEng: "SNT", nameKor: "스테이터스네트워크토큰" },
    { nameEng: "DAC", nameKor: "다빈치" },
    { nameEng: "ORBS", nameKor: "오브스" },
    { nameEng: "MBL", nameKor: "무비블록" },
    { nameEng: "ZRX", nameKor: "제로엑스" },
    { nameEng: "XEM", nameKor: "넴" },
    { nameEng: "BAT", nameKor: "베이직어텐션토큰" },
    { nameEng: "HDAC", nameKor: "에이치닥" },
    { nameEng: "MIX", nameKor: "믹스마블" },
    { nameEng: "STRAT", nameKor: "스트라티스" },
    { nameEng: "CTXC", nameKor: "코르텍스" }
  ];
  
  export const nameOfCoins3 = [
    { nameEng: "ICX", nameKor: "아이콘" },
    { nameEng: "NPXS", nameKor: "펀디엑스" },
    { nameEng: "POWR", nameKor: "파워렛저" },
    { nameEng: "IOST", nameKor: "이오스트" },
    { nameEng: "WAXP", nameKor: "왁스" },
    { nameEng: "TRUE", nameKor: "트루체인" },
    { nameEng: "WICC", nameKor: "웨이키체인" },
    { nameEng: "HYC", nameKor: "하이콘" },
    { nameEng: "BZNT", nameKor: "베잔트" },
    { nameEng: "WOM", nameKor: "왐토큰" },
    { nameEng: "FX", nameKor: "펑션엑스" },
    { nameEng: "LBA", nameKor: "크레드" },
    { nameEng: "WET", nameKor: "위쇼토큰" },
    { nameEng: "OGO", nameKor: "오리고" },
    { nameEng: "LOOM", nameKor: "룸네트워크" },
    { nameEng: "ZIL", nameKor: "질리카" },
    { nameEng: "CHR", nameKor: "크로미아" },
    { nameEng: "ITC", nameKor: "아이오티체인" },
    { nameEng: "DVP", nameKor: "디브이피" },
    { nameEng: "ELF", nameKor: "엘프" },
    { nameEng: "PCM", nameKor: "프레시움" },
    { nameEng: "KNC", nameKor: "카이버 네트워크" },
    { nameEng: "RNT", nameKor: "원루트 네트워크" },
    { nameEng: "ANKR", nameKor: "앵커" },
    { nameEng: "CRO", nameKor: "크립토닷컴체인" },
    { nameEng: "LRC", nameKor: "루프링" },
    { nameEng: "QKC", nameKor: "쿼크체인" },
    { nameEng: "SXP", nameKor: "스와이프" }
  ];

  export const upbitCoinList = [
    // 서버 1 (https://vc-fetch-server-01.herokuapp.com)
    {"name":"가스","symbol":"GAS", "server": "vc-fetch-server-01"},
    {"name":"아크","symbol":"ARK", "server": "vc-fetch-server-01"},
    {"name":"톤","symbol":"TON", "server": "vc-fetch-server-01"},
    {"name":"이그니스","symbol":"IGNIS", "server": "vc-fetch-server-01"},
    {"name":"시린토큰","symbol":"SRN", "server": "vc-fetch-server-01"},
    {"name":"코박토큰","symbol":"CBK", "server": "vc-fetch-server-01"},
    {"name":"네오","symbol":"NEO", "server": "vc-fetch-server-01"},
    {"name":"스펜드코인","symbol":"SPND", "server": "vc-fetch-server-01"},
    {"name":"아이오에스티","symbol":"IOST", "server": "vc-fetch-server-01"},

    // 서버 2 (https://vc-fetch-server-01.herokuapp.com)
    {"name":"페이코인","symbol":"PCI", "server": "vc-fetch-server-02"},
    {"name":"코모도","symbol":"KMD", "server": "vc-fetch-server-02"},
    {"name":"쎄타퓨엘","symbol":"TFUEL", "server": "vc-fetch-server-02"},
    {"name":"디카르고","symbol":"DKA", "server": "vc-fetch-server-02"},
    {"name":"썬더토큰","symbol":"TT", "server": "vc-fetch-server-02"},
    {"name":"아하토큰","symbol":"AHT", "server": "vc-fetch-server-02"},
    {"name":"디마켓","symbol":"DMT", "server": "vc-fetch-server-02"},
    {"name":"캐리프로토콜","symbol":"CRE", "server": "vc-fetch-server-02"},
    {"name":"엠블","symbol":"MVL", "server": "vc-fetch-server-02"},

    // 서버 3 (https://vc-fetch-server-03.herokuapp.com)
    {"name":"그로스톨코인","symbol":"GRS", "server": "vc-fetch-server-03"},
    {"name":"메인프레임","symbol":"MFT", "server": "vc-fetch-server-03"},
    {"name":"썸씽","symbol":"SSX", "server": "vc-fetch-server-03"},
    {"name":"헤데라해시그래프","symbol":"HBAR", "server": "vc-fetch-server-03"},
    {"name":"스톰엑스","symbol":"STMX", "server": "vc-fetch-server-03"},
    {"name":"리퍼리움","symbol":"RFR", "server": "vc-fetch-server-03"},
    {"name":"스토리지","symbol":"STORJ", "server": "vc-fetch-server-03"},
    {"name":"엘비알와이크레딧","symbol":"LBC", "server": "vc-fetch-server-03"},
    {"name":"센티넬프로토콜","symbol":"UPP", "server": "vc-fetch-server-03"},

    // 서버 4 (https://vc-fetch-server-04.herokuapp.com)
    {"name":"칠리즈","symbol":"CHZ", "server": "vc-fetch-server-04"},
    {"name":"에브리피디아","symbol":"IQ", "server": "vc-fetch-server-04"},
    {"name":"시빅","symbol":"CVC", "server": "vc-fetch-server-04"},
    {"name":"디센트럴랜드","symbol":"MANA", "server": "vc-fetch-server-04"},
    {"name":"트웰브쉽스","symbol":"TSHP", "server": "vc-fetch-server-04"},
    {"name":"엔도르","symbol":"EDR", "server": "vc-fetch-server-04"},
    {"name":"플레이댑","symbol":"PLA", "server": "vc-fetch-server-04"},
    {"name":"픽셀","symbol":"PXL", "server": "vc-fetch-server-04"},
    {"name":"메디블록","symbol":"MED", "server": "vc-fetch-server-04"},
    
    // {"name":"모스코인","symbol":"MOC"},
    // {"name":"휴먼스케이프","symbol":"HUM"},
    // {"name":"스팀달러","symbol":"SBD"},
    // {"name":"에드엑스","symbol":"ADX"},
    // {"name":"리스크","symbol":"LSK"},
    // {"name":"아르고","symbol":"AERGO"},
    // {"name":"솔브케어","symbol":"SOLVE"},
    // {"name":"알파쿼크","symbol":"AQT"},
    // {"name":"마로","symbol":"MARO"},

    // {"name":"시아코인","symbol":"SC"},
    // {"name":"헌트","symbol":"HUNT"},
    // {"name":"에스티피","symbol":"STPT"},
    // {"name":"아인스타이늄","symbol":"EMC2"},
    // {"name":"아더","symbol":"ARDR"},
    // {"name":"카바","symbol":"KAVA"},
    // {"name":"아이오타","symbol":"IOTA"},
    // {"name":"폴리매쓰","symbol":"POLY"},
]